_format_version: "2.1"
_transform: true

services:
  - name: auth-service
    url: http://auth:5000
    routes:
      - name: auth-login
        paths: ["/login", "/register", "/captcha"]
        methods: ["POST"]

  - name: orders-service
    url: http://orders:6000
    routes:
      - name: orders-api
        paths: ["/orders"]
        methods: ["GET", "POST", "PUT", "DELETE"]

  - name: frontend-proxy
    url: http://frontend:4200
    routes:
      - name: frontend
        paths: ["/"]
        strip_path: false

plugins:
  - name: rate-limiting
    service: auth-service
    config:
      minute: 20
      policy: local

  - name: cors
    route: frontend
    config:
      origins: ["*"]
      methods: ["GET", "POST", "PUT", "DELETE"]
      headers: ["Authorization", "Content-Type"]
